[package]
name = "query_pull_traits"
version = "0.0.1"
workspace = ".."
edition = "2024"

[lib]
name = "query_pull_traits"
path = "lib.rs"

[dependencies.thiserror]
workspace = true

[dependencies.core_traits]
path = "../core-traits"

[dependencies.db_traits]
path = "../db-traits"
