[package]
name = "query_algebrizer_traits"
version = "0.0.1"
workspace = ".."
edition = "2024"

[lib]
name = "query_algebrizer_traits"
path = "lib.rs"

[dependencies.thiserror]
workspace = true

[dependencies.edn]
path = "../edn"

[dependencies.core_traits]
path = "../core-traits"
